Egeroro/Egeroro.UI/Controllers/FleetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Egeroro.Business.Concrete;
using Egeroro.Data.EntityFramework;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Egeroro.UI.Controllers
{
    public class FleetController : Controller
    {
        FleetManager _fleetManager = new FleetManager(new EFFleetDal());
        // GET: /<controller>/
        public IActionResult Index()
        {
            var result = _fleetManager.GetList();
            return View(result);
        }

        public IActionResult Detail(int id)
        {
            var service = _fleetManager.GetById(id);
            if (service == null)
            {
                return NotFound();
            }
            return View(service);
        }
    }
}

Egeroro/Egeroro.UI/Views/Fleet/Detail.cshtml
@using Egeroro.Entity.Concrete
@model Fleet

<!-- Start of Breadcrumb section
    ============================================= -->
<section id="ft-breadcrumb" class="ft-breadcrumb-section position-relative" data-background="@Model.MainPageImage">
    <span class="background_overlay"></span>
    <span class="design-shape position-absolute"><img src="/assets/img/shape/tmd-sh.png" alt=""></span>
    <div class="container">
        <div class="ft-breadcrumb-content headline text-center position-relative">
            <h2>Ege Gaz-1</h2>
            <div class="ft-breadcrumb-list ul-li">
                <ul>
                    <li><a href="/">Ana Sayfa</a></li>
                    <li>Filomuz </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- End of Breadcrumb section
    ============================================= -->
<!-- Start of Project details  section
    ============================================= -->
<section id="ft-project-details" class="ft-project-details-section page-padding">
    <div class="container">
        <div class="ft-project-overview">
            <div class="row">
                <div class="col-lg-8">
                    <div class="ft-project-details-img">
                        <img src="@Model.Image" alt="">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="ft-portfolio-overview-text headline">
                        <div class="project-title-overview text-center">
                            <h3>Filo Bilgileri</h3>
                        </div>
                        <div class="ft-portfolio-overview-list-value">
                            <div class="ft-portfolio-overview-list  ul-li-block">
                                <ul>
                                    <li>Gemi Adı: <span>@Model.ShipName</span></li>
                                    <li>Bayrağı: <span>@Model.Flag</span></li>
                                    <li>Bağlama Limanı: <span>@Model.PortofRegistry</span></li>
                                    <li>Yolcu Kapasitesi:  <span>@Model.PassengerCapacity</span></li>
                                    <li>Grt:  <span>@Model.GrossRegisterTonnage</span></li>
                                    <li>Dwt:  <span>@Model.DeadweightTonnage</span></li>
                                    <li>Tam Boy:  <span>@Model.OverallLength m</span></li>
                                    <li>Kütük Eni:  <span>@Model.Beam m</span></li>
                                    <li>Max. Sürat:  <span>@Model.MaxSpeed kn</span></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ft-project-overview-text-wrapper headline pera-content">
            <h3>
                @Model.ShipName
            </h3>

        </div>
    </div>
</section>
<!-- End of Project details section
    ============================================= -->


<script src="assets/js/jquery.nice-select.min.js"></script>
<script src="assets/js/knob.js"></script>
<script src="assets/js/gmaps.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDk2HrmqE4sWSei0XdKGbOMOHN3Mm2Bf-M&amp;ver=2.1.6"></script>

Egeroro/Egeroro.UI/Views/Fleet/Index.cshtml
@using Egeroro.Entity.Concrete
@model List<Fleet>
<!-- Start of Breadcrumb section
    ============================================= -->
<section id="ft-breadcrumb" class="ft-breadcrumb-section position-relative" data-background="@Model.First().MainPageImage">
    <span class="background_overlay"></span>
    <span class="design-shape position-absolute"><img src="/assets/img/shape/tmd-sh.png" alt=""></span>
    <div class="container">
        <div class="ft-breadcrumb-content headline text-center position-relative">
            <h2>Filomuz</h2>
            <div class="ft-breadcrumb-list ul-li">
                <ul>
                    <li><a href="/">Ana Sayfa</a></li>
                    <li>Filomuz</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- End of Breadcrumb section
    ============================================= -->
<!-- Start of Service page section
    ============================================= -->
<section id="ft-service-page" class="ft-service-page-section page-padding">
    <div class="container">

        <div class="ft-service-page-items">
            <div class="row">
                @{ int count = 1;}
                @foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-6">
                        <div class="ft-service-innerbox-2 position-relative">
                            <div class="ft-service-img text-center">
                                <a href="@Url.Action("Detail", "Fleet", new {id = item.Id})">
                                    <img src="@item.Image" alt="">
                                </a>
                            </div>
                            <div class="ft-service-text position-relative headline">
                                <h3><a href="#">@item.ShipName</a></h3>
                                <div class="ft-btn-2">
                                    <a href="@Url.Action("Detail", "Fleet", new {id = item.Id})">
                                        <i class="icon-first flaticon-right-arrow"></i>
                                        <span>Detay</span>
                                    </a>
                                </div>
                            </div>
                            <div class="ft-service-serial position-absolute">
                                @count
                            </div>
                        </div>
                    </div>
                    count++;
                }

                @*<div class="col-lg-4 col-md-6">
                        <div class="ft-service-innerbox-2 position-relative">
                            <div class="ft-service-img text-center">
                                <a href="ege-gaz-1.html">
                                    <img src="/assets/img/service/ege-gaz-1.jpg" alt="">
                                </a>
                            </div>
                            <div class="ft-service-text position-relative headline">
                                <h3><a href="#">Ege Gaz-1</a></h3>
                                <div class="ft-btn-2">
                                    <a href="ege-gaz-1.html">
                                        <i class="icon-first flaticon-right-arrow"></i>
                                        <span>Detay</span>
                                    </a>
                                </div>
                            </div>
                            <div class="ft-service-serial position-absolute">
                                1
                            </div>
                        </div>
                    </div>



                    <div class="col-lg-4 col-md-6">
                        <div class="ft-service-innerbox-2 position-relative">
                            <div class="ft-service-img text-center">
                                <a href="ege-gaz-3.html">
                                    <img src="/assets/img/service/ege-gaz-3.jpg" alt="">
                                </a>
                            </div>
                            <div class="ft-service-text position-relative headline">
                                <h3><a href="#">Ege Gaz-3</a></h3>
                                <div class="ft-btn-2">
                                    <a href="ege-gaz-3.html">
                                        <i class="icon-first flaticon-right-arrow"></i>
                                        <span>Detay</span>
                                    </a>
                                </div>
                            </div>
                            <div class="ft-service-serial position-absolute">
                                2
                            </div>
                        </div>
                    </div>


                    <div class="col-lg-4 col-md-6">
                        <div class="ft-service-innerbox-2 position-relative">
                            <div class="ft-service-img text-center">
                                <a href="yener-ciner.html">
                                    <img src="/assets/img/service/yener-ciner.jpg" alt="">
                                </a>
                            </div>
                            <div class="ft-service-text position-relative headline">
                                <h3><a href="#">Yener Ciner</a></h3>
                                <div class="ft-btn-2">
                                    <a href="yener-ciner.html">
                                        <i class="icon-first flaticon-right-arrow"></i>
                                        <span>Detay</span>
                                    </a>
                                </div>
                            </div>
                            <div class="ft-service-serial position-absolute">
                                3
                            </div>
                        </div>
                    </div>*@




            </div>



        </div>
    </div>
</section>
<!-- End of Service page section
    ============================================= -->