Egeroro/Egeroro.UI/Controllers/OurServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Egeroro.Business.Concrete;
using Egeroro.Data.EntityFramework;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Egeroro.UI.Controllers
{
    public class OurServicesController : Controller
    {
        OurServicesManager _ourServicesManager = new OurServicesManager(new EFOurServicesDal());
        // GET: /<controller>/
        public IActionResult Index()
        {
            var result = _ourServicesManager.GetList();
            return View(result);
        }
        
        public IActionResult Detail(int id)
        {
            var service = _ourServicesManager.GetById(id);
            if (service == null)
            {
                return NotFound();
            }
            return View(service);
        }
    }
}

Egeroro/Egeroro.UI/Views/Shared/Components/_OurServices/Default.cshtml
@using Egeroro.Entity.Concrete
@model List<OurServices>
<section id="ft-service-3" class="ft-service-section-3" style="padding-top: 60px;">
    <div class="container">
        <div class="ft-section-title-3 headline text-center wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">

            <h2>Hizmetlerimiz</h2>
        </div>
        <div class="ft-service-content-3">
            <div class="ft-service-content-items-3">
                <div class="row justify-content-center">
                    @foreach (var item in Model)
                    {
                        <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
                            <div class="ft-service-innerbox-3 position-relative">
                                <div class="ft-service-img position-relative">
                                    <img src="@item.Image" alt="">
                                </div>
                                <div class="ft-service-text-icon position-relative">
                                    <div class="ft-service-icon d-flex align-items-center justify-content-center position-absolute">
                                        <i class="@item.IconUrl"></i>
                                    </div>
                                    <div class="ft-service-text position-relative headline pera-content">
                                        <h3>
                                            <a href="@Url.Action("Detail", "OurServices", new {id = item.Id})">
                                                @item.Title
                                            </a>
                                        </h3>
                                        <p>
                                            @item.Description
                                        </p>
                                    </div>
                                </div>
                                <div class="more-btn position-absolute">
                                    <a class="d-flex align-items-center justify-content-center" href="@Url.Action("Detail", "OurServices", new {id = item.Id})">Detay <i class="far fa-arrow-right"></i></a>
                                </div>
                            </div>
                        </div>
                    }
                    @*<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
            <div class="ft-service-innerbox-3 position-relative">
                <div class="ft-service-img position-relative">
                    <img src="/assets/img/service/tehlikeli-madde-roro-hizmetleri.jpg" alt="">
                </div>
                <div class="ft-service-text-icon position-relative">
                    <div class="ft-service-icon d-flex align-items-center justify-content-center position-absolute">
                        <i class="flaticon-plane"></i>
                    </div>
                    <div class="ft-service-text position-relative headline pera-content">
                        <h3>
                            <a href="tehlikeli-madde-roro-hizmetleri.html">
                                Tehlikeli Madde Roro Hizmetleri
                            </a>
                        </h3>
                        <p>
                            Maltepe İDO İskelesi ve Zeytinburnu Zeyport Limanları arasında deniz yoluyla yapılacak tehlikeli madde taşımacılığı faaliyetlerinin ekonomik, seri, güvenli, kaliteli, çevreye olumsuz etkisi en az ve diğer taşımacılık faaliyetleri ile uyumlu şekilde yapılmasını sağlamak için çalışmaktayız.
                        </p>
                    </div>
                </div>
                <div class="more-btn position-absolute">
                    <a class="d-flex align-items-center justify-content-center" href="tehlikeli-madde-roro-hizmetleri.html">Detay <i class="far fa-arrow-right"></i></a>
                </div>
            </div>
        </div>*@
                    @*<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="200ms" data-wow-duration="1500ms">
            <div class="ft-service-innerbox-3 position-relative">
                <div class="ft-service-img position-relative">
                    <img src="/assets/img/service/proje-tasimaciligi.jpg" alt="">
                </div>
                <div class="ft-service-text-icon position-relative">
                    <div class="ft-service-icon d-flex align-items-center justify-content-center position-absolute">
                        <i class="flaticon-boat"></i>
                    </div>
                    <div class="ft-service-text position-relative headline pera-content">
                        <h3>
                            <a href="proje-tasimaciligi.html">
                                Proje Taşımacılıgı
                            </a>
                        </h3>
                        <p>
                            Proje Taşımacılığı’nın esası, standart dışı ölçülerdeki ağır yüklerin, bir noktadan diğer noktaya standart dışı şekilde taşımaya dayanmaktadır. Bizler Ege Roro olarak; standart dışı yükleri, müşterinin ihtiyaçları ve istekleri doğrultusunda, en kısa zamanda ve en uygun taşıma yöntemini kullanarak hedefe ulaştırmaktayız.
                        </p>
                    </div>
                </div>
                <div class="more-btn position-absolute">
                    <a class="d-flex align-items-center justify-content-center" href="proje-tasimaciligi.html">Detay <i class="far fa-arrow-right"></i></a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="400ms" data-wow-duration="1500ms">
            <div class="ft-service-innerbox-3 position-relative">
                <div class="ft-service-img position-relative">
                    <img src="/assets/img/service/prens-adalari.jpg" alt="">
                </div>
                <div class="ft-service-text-icon position-relative">
                    <div class="ft-service-icon d-flex align-items-center justify-content-center position-absolute">
                        <i class="flaticon-free-shipping"></i>
                    </div>
                    <div class="ft-service-text position-relative headline pera-content">
                        <h3>
                            <a href="prens-adalari.html">
                                Prens Adaları Seferleri
                            </a>
                        </h3>
                        <p>
                            Feribotlarımız Büyükada, Kınalıada, Heybeliada, Yassıada ve Burgazada olmak üzere tüm Prens Adaları’na ihtiyaç olması halinde kamyon, taksi, minibüs ve resmi araçlar olmak üzere her türlü motorlu aracı İstanbul Büyükşehir Belediyesi tarafından onaylanan taşıma ruhsatnamesine istinaden taşımaya tam yetkilidir.
                        </p>
                    </div>
                </div>
                <div class="more-btn position-absolute">
                    <a class="d-flex align-items-center justify-content-center" href="prens-adalari.html">Detay <i class="far fa-arrow-right"></i></a>
                </div>
            </div>
        </div>*@
                </div>
            </div>

        </div>
    </div>
</section>